"""added is_paper_authorizerd in publish_paper

Revision ID: 1423d8814f6b
Revises: 7357514d2d61
Create Date: 2022-03-16 12:33:54.607241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1423d8814f6b'
down_revision = '7357514d2d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_paper', sa.Column('is_paper_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_paper', 'is_paper_authorized')
    # ### end Alembic commands ###
