"""created faculty profile table

Revision ID: 20729dc5748c
Revises: 1423d8814f6b
Create Date: 2022-03-17 20:15:23.260476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20729dc5748c'
down_revision = '1423d8814f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('linkedin', sa.String(length=150), nullable=True),
    sa.Column('github', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('work_exp', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty')
    # ### end Alembic commands ###
