"""constraints for dept_area and paper_type only

Revision ID: 2cc351062533
Revises: e5eb3ef94842
Create Date: 2022-02-24 21:45:43.619765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc351062533'
down_revision = 'e5eb3ef94842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_paper', sa.Column('paper_type_id', sa.Integer(), nullable=False))
    op.add_column('publish_paper', sa.Column('department_area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'publish_paper', 'department_areas', ['department_area_id'], ['id'])
    op.create_foreign_key(None, 'publish_paper', 'paper_type', ['paper_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publish_paper', type_='foreignkey')
    op.drop_constraint(None, 'publish_paper', type_='foreignkey')
    op.drop_column('publish_paper', 'department_area_id')
    op.drop_column('publish_paper', 'paper_type_id')
    # ### end Alembic commands ###
