"""added user constraint to faculty

Revision ID: 4c05cdf55930
Revises: 20729dc5748c
Create Date: 2022-03-17 20:24:29.191382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c05cdf55930'
down_revision = '20729dc5748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faculty', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.drop_column('faculty', 'user_id')
    # ### end Alembic commands ###
