"""departments table

Revision ID: 60db7bc8c61e
Revises: c0c09cc2a96d
Create Date: 2022-02-24 20:47:57.508338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60db7bc8c61e'
down_revision = 'c0c09cc2a96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
