"""added access in paper

Revision ID: 7357514d2d61
Revises: 68b60362cfc0
Create Date: 2022-03-16 11:31:57.183623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from repository.models import PaperAccessEnum

# revision identifiers, used by Alembic.
revision = '7357514d2d61'
down_revision = '68b60362cfc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    paper_access = postgresql.ENUM(PaperAccessEnum, name="access")
    paper_access.create(op.get_bind(), checkfirst=True)
    op.add_column('publish_paper', sa.Column('access',  paper_access))
    # op.add_column('publish_paper', sa.Column('access', sa.Enum('ALLOW_ALL', 'ONLY_YOUR_COLLEGE', 'ONLY_FACULTIES', name='paperaccessenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    paper_access = postgresql.ENUM(PaperAccessEnum, name="access")
    paper_access.drop(op.get_bind())
    # op.drop_column('publish_paper', 'access')
    # ### end Alembic commands ###
