"""conference attended field

Revision ID: 85b62fa0e490
Revises: 5996797a4e0e
Create Date: 2022-03-26 00:52:46.364417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b62fa0e490'
down_revision = '5996797a4e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('conference_attended', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'conference_attended')
    # ### end Alembic commands ###
