"""citations tree associaltion table

Revision ID: 9a8d63327d1a
Revises: f5678d37fb8c
Create Date: 2022-05-15 16:17:40.841255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8d63327d1a'
down_revision = 'f5678d37fb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations_tree',
    sa.Column('citedby_id', sa.Integer(), nullable=True),
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['publish_paper.id'], ),
    sa.ForeignKeyConstraint(['citedby_id'], ['publish_paper.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations_tree')
    # ### end Alembic commands ###
