"""created currently working field

Revision ID: b4cdfae27790
Revises: 4c05cdf55930
Create Date: 2022-03-25 23:38:34.927361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cdfae27790'
down_revision = '4c05cdf55930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('currently_working', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'currently_working')
    # ### end Alembic commands ###
