"""updated unique paper id unique constraint

Revision ID: f5678d37fb8c
Revises: 49c0dae3a9b2
Create Date: 2022-04-24 17:06:40.439088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5678d37fb8c'
down_revision = '49c0dae3a9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'publish_paper', ['unique_paper_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publish_paper', type_='unique')
    # ### end Alembic commands ###
